[package]
name = "brunch-tools-daemon"
version = "0.1.3"
authors = ["xeu100 <me@xeu100.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.13.0"
whoami = "1.1"
json="0.12"
duct="0.13"