name: daemon
description: A Dart rewrite of the Brunch Tools Daemon
version: 2.0.0
homepage: https://brunch.tools

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
