name: Rust
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Code
      run: cargo build --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: brunch-tools-daemon
        path: target/debug/brunch-tools-daemon
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{CARGO_MAKE_CRATE_VERSION}}-${{run_number}}
        release_name: Prerelease v${{CARGO_MAKE_CRATE_VERSION}}
        body: |
          Note: This is an automatic prerelease build from GitHub actions. It may be unstable and is not recommended for normal users.
        draft: false
        prerelease: true
